OLMIS-6558: Introduce new env variable - PUBLIC_URL
OpenLMIS/openlmis-notification pull request #3
Opened 2019-09-09 12:12 UTC by mwedel

2019-09-09 13:49 UTC, lukaslew requested changes

2019-09-09 13:49 UTC, lukaslew commented on CHANGELOG.md
> +4.2.2 / WIP
should be 4.2.0

2019-09-09 13:49 UTC, lukaslew commented on gradle.properties
> +serviceVersion=4.2.2-SNAPSHOT
4.2.0

2019-09-10 05:05 UTC, lukaslew approved these changes

2019-09-10 09:58 UTC, matkwiatkowski approved these changes

2019-09-10 09:58 UTC, merged